PRODUCT_COPY_FILES += \
    vendor/qcom/prebuilt/proprietary/adreno/a3xx/system/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/qcom/prebuilt/proprietary/adreno/a3xx/system/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/qcom/prebuilt/proprietary/adreno/a3xx/system/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/qcom/prebuilt/proprietary/adreno/a3xx/system/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/qcom/prebuilt/proprietary/adreno/a3xx/system/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/qcom/prebuilt/proprietary/adreno/a3xx/system/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/qcom/prebuilt/proprietary/adreno/a3xx/system/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/qcom/prebuilt/proprietary/adreno/a3xx/system/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/qcom/prebuilt/proprietary/adreno/a3xx/system/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/qcom/prebuilt/proprietary/adreno/a3xx/system/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/qcom/prebuilt/proprietary/adreno/a3xx/system/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/qcom/prebuilt/proprietary/adreno/a3xx/system/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/qcom/prebuilt/proprietary/adreno/a3xx/system/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/qcom/prebuilt/proprietary/adreno/a3xx/system/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/qcom/prebuilt/proprietary/adreno/a3xx/system/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/qcom/prebuilt/proprietary/adreno/a3xx/system/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/qcom/prebuilt/proprietary/adreno/a3xx/system/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
    vendor/qcom/prebuilt/proprietary/adreno/a3xx/system/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/bin/irsc_util:system/vendor/bin/irsc_util \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/bin/mlog_qmi_service:system/vendor/bin/mlog_qmi_service \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/bin/mm-qcamera-daemon:system/vendor/bin/mm-qcamera-daemon \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/bin/netmgrd:system/vendor/bin/netmgrd \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/bin/pm-proxy:system/vendor/bin/pm-proxy \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/bin/pm-service:system/vendor/bin/pm-service \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/bin/qmuxd:system/vendor/bin/qmuxd \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/bin/qseecomd:system/vendor/bin/qseecomd \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/bin/rmt_storage:system/vendor/bin/rmt_storage \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/bin/sct_service:system/vendor/bin/sct_service \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/bin/sensors.qcom:system/vendor/bin/sensors.qcom \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/bin/ta_qmi_service:system/vendor/bin/ta_qmi_service \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/bin/tad_static:system/vendor/bin/tad_static \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/hw/sensors.msm8974.so:system/vendor/lib/hw/sensors.msm8974.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libactuator_bu64291gwz.so:system/vendor/lib/libactuator_bu64291gwz.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libactuator_bu64291gwz_camcorder.so:system/vendor/lib/libactuator_bu64291gwz_camcorder.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libactuator_bu64291gwz_camera.so:system/vendor/lib/libactuator_bu64291gwz_camera.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libactuator_bu64295g.so:system/vendor/lib/libactuator_bu64295g.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libactuator_bu64295g_camcorder.so:system/vendor/lib/libactuator_bu64295g_camcorder.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libactuator_bu64295g_camera.so:system/vendor/lib/libactuator_bu64295g_camera.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libactuator_bu64296g.so:system/vendor/lib/libactuator_bu64296g.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libactuator_bu64296g_camcorder.so:system/vendor/lib/libactuator_bu64296g_camcorder.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libactuator_bu64296g_camera.so:system/vendor/lib/libactuator_bu64296g_camera.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libactuator_dw9719.so:system/vendor/lib/libactuator_dw9719.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libactuator_dw9719_camcorder.so:system/vendor/lib/libactuator_dw9719_camcorder.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libactuator_dw9719_camera.so:system/vendor/lib/libactuator_dw9719_camera.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromaflash.so:system/vendor/lib/libchromaflash.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx132_common.so:system/vendor/lib/libchromatix_imx132_common.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx132_cpp_liveshot.so:system/vendor/lib/libchromatix_imx132_cpp_liveshot.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx132_cpp_preview.so:system/vendor/lib/libchromatix_imx132_cpp_preview.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx132_cpp_snapshot.so:system/vendor/lib/libchromatix_imx132_cpp_snapshot.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx132_cpp_video.so:system/vendor/lib/libchromatix_imx132_cpp_video.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx132_default_video.so:system/vendor/lib/libchromatix_imx132_default_video.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx132_liveshot.so:system/vendor/lib/libchromatix_imx132_liveshot.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx132_postproc.so:system/vendor/lib/libchromatix_imx132_postproc.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx132_preview.so:system/vendor/lib/libchromatix_imx132_preview.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx132_snapshot.so:system/vendor/lib/libchromatix_imx132_snapshot.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx134_common.so:system/vendor/lib/libchromatix_imx134_common.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx134_cpp_liveshot.so:system/vendor/lib/libchromatix_imx134_cpp_liveshot.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx134_cpp_preview.so:system/vendor/lib/libchromatix_imx134_cpp_preview.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx134_cpp_snapshot.so:system/vendor/lib/libchromatix_imx134_cpp_snapshot.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx134_cpp_video.so:system/vendor/lib/libchromatix_imx134_cpp_video.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx134_default_video.so:system/vendor/lib/libchromatix_imx134_default_video.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx134_liveshot.so:system/vendor/lib/libchromatix_imx134_liveshot.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx134_postproc.so:system/vendor/lib/libchromatix_imx134_postproc.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx134_preview.so:system/vendor/lib/libchromatix_imx134_preview.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx134_snapshot.so:system/vendor/lib/libchromatix_imx134_snapshot.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx200_common.so:system/vendor/lib/libchromatix_imx200_common.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx200_cpp_liveshot.so:system/vendor/lib/libchromatix_imx200_cpp_liveshot.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx200_cpp_preview.so:system/vendor/lib/libchromatix_imx200_cpp_preview.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx200_cpp_snapshot.so:system/vendor/lib/libchromatix_imx200_cpp_snapshot.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx200_cpp_video.so:system/vendor/lib/libchromatix_imx200_cpp_video.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx200_default_video.so:system/vendor/lib/libchromatix_imx200_default_video.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx200_liveshot.so:system/vendor/lib/libchromatix_imx200_liveshot.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx200_postproc.so:system/vendor/lib/libchromatix_imx200_postproc.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx200_preview.so:system/vendor/lib/libchromatix_imx200_preview.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libchromatix_imx200_snapshot.so:system/vendor/lib/libchromatix_imx200_snapshot.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libflash_pmic.so:system/vendor/lib/libflash_pmic.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libllvd_smore.so:system/vendor/lib/libllvd_smore.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libloc_api_v02.so:system/vendor/lib/libloc_api_v02.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libloc_ds_api.so:system/vendor/lib/libloc_ds_api.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmiscta.so:system/vendor/lib/libmiscta.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera2_pp_buf_mgr.so:system/vendor/lib/libmmcamera2_pp_buf_mgr.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera2_q3a_core.so:system/vendor/lib/libmmcamera2_q3a_core.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera2_sensor_debug.so:system/vendor/lib/libmmcamera2_sensor_debug.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_cac2_lib.so:system/vendor/lib/libmmcamera_cac2_lib.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_chromaflash_lib.so:system/vendor/lib/libmmcamera_chromaflash_lib.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_eeprom_util.so:system/vendor/lib/libmmcamera_eeprom_util.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_eztune_module.so:system/vendor/lib/libmmcamera_eztune_module.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_imx132.so:system/vendor/lib/libmmcamera_imx132.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_imx134.so:system/vendor/lib/libmmcamera_imx134.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_imx134a.so:system/vendor/lib/libmmcamera_imx134a.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_imx200a.so:system/vendor/lib/libmmcamera_imx200a.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_imx200b.so:system/vendor/lib/libmmcamera_imx200b.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_abf40.so:system/vendor/lib/libmmcamera_isp_abf40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_bcc40.so:system/vendor/lib/libmmcamera_isp_bcc40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_be_stats44.so:system/vendor/lib/libmmcamera_isp_be_stats44.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_bf_stats40.so:system/vendor/lib/libmmcamera_isp_bf_stats40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_bg_stats44.so:system/vendor/lib/libmmcamera_isp_bg_stats44.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_bhist_stats44.so:system/vendor/lib/libmmcamera_isp_bhist_stats44.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_bpc40.so:system/vendor/lib/libmmcamera_isp_bpc40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_chroma_enhan40.so:system/vendor/lib/libmmcamera_isp_chroma_enhan40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_chroma_suppress40.so:system/vendor/lib/libmmcamera_isp_chroma_suppress40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_clamp_encoder40.so:system/vendor/lib/libmmcamera_isp_clamp_encoder40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_clamp_video40.so:system/vendor/lib/libmmcamera_isp_clamp_video40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so:system/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_color_correct40.so:system/vendor/lib/libmmcamera_isp_color_correct40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_color_xform_encoder40.so:system/vendor/lib/libmmcamera_isp_color_xform_encoder40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_color_xform_viewfinder40.so:system/vendor/lib/libmmcamera_isp_color_xform_viewfinder40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_cs_stats44.so:system/vendor/lib/libmmcamera_isp_cs_stats44.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_demosaic40.so:system/vendor/lib/libmmcamera_isp_demosaic40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_demux40.so:system/vendor/lib/libmmcamera_isp_demux40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_fovcrop_encoder40.so:system/vendor/lib/libmmcamera_isp_fovcrop_encoder40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_fovcrop_viewfinder40.so:system/vendor/lib/libmmcamera_isp_fovcrop_viewfinder40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_gamma40.so:system/vendor/lib/libmmcamera_isp_gamma40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_ihist_stats44.so:system/vendor/lib/libmmcamera_isp_ihist_stats44.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_linearization40.so:system/vendor/lib/libmmcamera_isp_linearization40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_luma_adaptation40.so:system/vendor/lib/libmmcamera_isp_luma_adaptation40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_mce40.so:system/vendor/lib/libmmcamera_isp_mce40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_mesh_rolloff40.so:system/vendor/lib/libmmcamera_isp_mesh_rolloff40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_rs_stats44.so:system/vendor/lib/libmmcamera_isp_rs_stats44.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_scaler_encoder40.so:system/vendor/lib/libmmcamera_isp_scaler_encoder40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_scaler_viewfinder40.so:system/vendor/lib/libmmcamera_isp_scaler_viewfinder40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_sce40.so:system/vendor/lib/libmmcamera_isp_sce40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_sub_module.so:system/vendor/lib/libmmcamera_isp_sub_module.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_isp_wb40.so:system/vendor/lib/libmmcamera_isp_wb40.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_llvd.so:system/vendor/lib/libmmcamera_llvd.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_optizoom_lib.so:system/vendor/lib/libmmcamera_optizoom_lib.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_pdaf.so:system/vendor/lib/libmmcamera_pdaf.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_pdafcamif.so:system/vendor/lib/libmmcamera_pdafcamif.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_ppbase_module.so:system/vendor/lib/libmmcamera_ppbase_module.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_stillmore_lib.so:system/vendor/lib/libmmcamera_stillmore_lib.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_trueportrait_lib.so:system/vendor/lib/libmmcamera_trueportrait_lib.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_ubifocus_lib.so:system/vendor/lib/libmmcamera_ubifocus_lib.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmcamera_vpu_module.so:system/vendor/lib/libmmcamera_vpu_module.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libmmqjpegdma.so:system/vendor/lib/libmmqjpegdma.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/liboptizoom.so:system/vendor/lib/liboptizoom.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libqomx_jpegenc_pipe.so:system/vendor/lib/libqomx_jpegenc_pipe.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libril-qc-qmi-2.so:system/vendor/lib/libril-qc-qmi-2.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libseemore.so:system/vendor/lib/libseemore.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libtrueportrait.so:system/vendor/lib/libtrueportrait.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libubifocus.so:system/vendor/lib/libubifocus.so \
    vendor/qcom/prebuilt/proprietary/msm8974/system/vendor/lib/libxml.so:system/vendor/lib/libxml.so \

